{
 "title": "Monzo Transactions",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "monzo_bucket" }
  ]
 },
 "panels": [
  {
   "title": "Debit - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transactions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"abs_amount\")\n  |> filter(fn: (r) => r[\"_value\"] <= 250)\n  |> filter(fn: (r) => r.type == \"DEBIT\")\n  |> group(columns: [\"type\"])\n  |> count(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Debit - Sum",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transactions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"abs_amount\")\n  |> filter(fn: (r) => r[\"_value\"] <= 250)\n  |> filter(fn: (r) => r.type == \"DEBIT\")\n  |> group(columns: [\"type\"])\n  |> sum(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Credit - Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transactions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"abs_amount\")\n  |> filter(fn: (r) => r[\"_value\"] <= 250)\n  |> filter(fn: (r) => r.type == \"CREDIT\")\n  |> group(columns: [\"type\"])\n  |> count(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Credit - Sum",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transactions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"abs_amount\")\n  |> filter(fn: (r) => r[\"_value\"] <= 250)\n  |> filter(fn: (r) => r.type == \"CREDIT\")\n  |> group(columns: [\"type\"])\n  |> sum(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Transactions DEBIT/CREDIT - PER DAY",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transactions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"abs_amount\")\n  |> group(columns: [\"type\"])\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "VALUE - DEBIT Transactions by Category",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transactions\" and r._field == \"abs_amount\")\n  |> filter(fn: (r) => r[\"type\"] == \"DEBIT\")\n  |> group()"
    }
   ]
  },
  {
   "title": "COUNT - DEBIT Transactions by Category",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"transactions\" and r._field == \"abs_amount\")\n  |> filter(fn: (r) => r[\"type\"] == \"DEBIT\")\n  |> group()"
    }
   ]
  },
  {
   "title": "Lower Value Transactions by Name (<120)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transactions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"abs_amount\")\n  |> filter(fn: (r) => r[\"_value\"] <= 250)\n  |> group(columns: [\"type\", \"name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lower Value Transactions by Name (<120)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transactions\")\n  |> filter(fn: (r) => r[\"_field\"] == \"abs_amount\")\n  |> filter(fn: (r) => r[\"_value\"] <= 250)\n  |> group(columns: [\"type\", \"name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group()\n  |> keep(columns: [\"name\",\"type\", \"value\",\"_value\",\"_field\",\"_time\"])\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Higher Value DEBIT Transactions (>£250)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"type\"] == \"DEBIT\")\n  |> filter(fn: (r) => r[\"_value\"] > 250)\n  |> group(columns: [\"name\"])\n"
    }
   ]
  },
  {
   "title": "Transaction Count from Monzo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"transaction-count\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => r[\"period\"] == \"30\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}